"""add connected and last_connected_at to accounts

Revision ID: aea41dbc2023
Revises: 4475cecbaf67
Create Date: 2026-04-18 21:44:24.028190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aea41dbc2023'
down_revision: Union[str, Sequence[str], None] = '4475cecbaf67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('connected', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('accounts', sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'last_connected_at')
    op.drop_column('accounts', 'connected')
    # ### end Alembic commands ###
